### ISSUE TITLE
Apply conversion for common types

### ISSUE THREAD

**Issue by felipenoris** [felipenoris/XLSX.jl#191]

**Comment by nilshg** [comment]
I was about to open an issue which I feel I've opened before, but I can't seem to find it and the title of this issue seems close to what I'm after: 

When doing `infer_eltypes = true` on a column which in Excel has integers and floats, `XLSX.jl` currently returns `Any`. I think it would make sense to promote integers here, as in most cases this is likely what the user expects. Would this be covered by the "common conversions" that this issue is about or should I open a seperate issue (or would you not entertain this suggestion at all?)

**Comment by felipenoris** [comment]
#206 tried to implement support for `AbstractString` by redefining `CellValueType`.
I guess the ideal approach will be to keep `CellValueType` with concrete types (the types returned from reading a file) and applying conversion to abstract types on *set data* function calls.
