### ISSUE TITLE
Add helper methods for DataFrames

### ISSUE THREAD

**Issue by felipenoris** [felipenoris/XLSX.jl#55]
All table methods avoid using DataFrames directly. I'm planning to add some helper methods to bring some sugar to the code. But this will add a depencency on DataFrames. Would like to know if someone is against this.

**Comment by YongHee-Kim** [comment]
Yes I'm always using DataFrame, whenever I need to load something from Excel files, But I'm against add dependency on DataFrame. Because `DataFrame` is too widely used package, and It is quite likely that `DataFrame` would have major structural changes in the future for one reason or another. 
I've used ExcelReaders before, and package author [dropped DataFrame support](https://github.com/queryverse/ExcelReaders.jl/issues/45) after [nullable & missing refactoring](https://github.com/JuliaData/Missings.jl/issues/5)

**Comment by felipenoris** [comment]
Good to hear that! I guess I'll just leave this idea behind. Maybe I'll come back to this when Julia has native support for solutions like https://github.com/MikeInnes/Requires.jl .
